// <auto-generated />
namespace AddressBook.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatedDateOfBirthField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedDateOfBirthField));
        
        string IMigrationMetadata.Id
        {
            get { return "202003041655576_updatedDateOfBirthField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
